In [ ]:
from google.colab import drive
drive.mount('/content/drive')
URL = "/content/drive/MyDrive/235757_HAICon2021_dataset.zip (Unzipped Files)"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!pip install ./eTaPR-21.8.2-py3-none-any.whl

Processing ./eTaPR-21.8.2-py3-none-any.whl


In [ ]:
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from tqdm.notebook import trange
#from TaPR_pkg import etapr
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
import time
from scipy import signal

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import load_model
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

In [ ]:

TRAIN_DATASET = sorted([x for x in Path(URL+"/train/").glob("*.csv")])
TRAIN_DATASET

VALIDATION_DATASET = sorted([x for x in Path(URL+"/validation/").glob("*.csv")])
VALIDATION_DATASET

TEST_DATASET = sorted([x for x in Path(URL+"/test/").glob("*.csv")])
TEST_DATASET

[PosixPath('/content/drive/MyDrive/235757_HAICon2021_dataset.zip (Unzipped Files)/test/test1.csv'),
 PosixPath('/content/drive/MyDrive/235757_HAICon2021_dataset.zip (Unzipped Files)/test/test2.csv'),
 PosixPath('/content/drive/MyDrive/235757_HAICon2021_dataset.zip (Unzipped Files)/test/test3.csv')]

In [ ]:
def dataframe_from_csv(target):
    return pd.read_csv(target, engine='python').rename(columns=lambda x: x.strip())

def dataframe_from_csvs(targets):
    return pd.concat([dataframe_from_csv(x) for x in targets])

In [ ]:
TRAIN_DF_RAW = dataframe_from_csvs(TRAIN_DATASET)
TRAIN_DF_RAW

timestamp     C01  C02       C03  ...         C83   C84  C85   C86
0       2021-07-11 10:00:00 -2.2642    0  12.26196  ...  1014.79321  12.0   50  3506
1       2021-07-11 10:00:01 -2.4923    0  12.26196  ...  1014.79321  12.0   50  3493
2       2021-07-11 10:00:02 -2.8460    0  12.26196  ...  1014.79321  12.0   50  3490
3       2021-07-11 10:00:03 -2.1235    0  12.26196  ...  1014.79321  12.0   50  3525
4       2021-07-11 10:00:04 -2.9074    0  12.26196  ...  1014.79321  12.0   50  3503
...                     ...     ...  ...       ...  ...         ...   ...  ...   ...
259195  2021-08-09 08:59:56 -2.0065    0  12.26196  ...   986.05908  12.0   50   136
259196  2021-08-09 08:59:57 -2.2101    0  12.26196  ...   986.05908  12.0   50    89
259197  2021-08-09 08:59:58 -2.3325    0  12.26196  ...   986.05908  12.0   50    90
259198  2021-08-09 08:59:59 -2.3049    0  12.26196  ...   986.05908  12.0   50    74
259199  2021-08-09 09:00:00 -2.2011    0  12.26196  ...   986.05908  12.0   50   101

[1004402 rows x 87 columns]

In [ ]:
# import datetime


# TRAIN_DF_RAW['day'] = TRAIN_DF_RAW['timestamp'].map(lambda x: int(x[8:10]))
# TRAIN_DF_RAW['month'] = TRAIN_DF_RAW['timestamp'].map(lambda x: int(x[5:7]))

# TRAIN_DF_RAW['day']

# TRAIN_DF = TRAIN_DF_RAW[(TRAIN_DF_RAW['day'] < 22) & (TRAIN_DF_RAW['month'] == 7)]
# TRAIN_DF

In [ ]:
def plot(column, s=10):
    plt.figure(figsize=(20, 4))
    plt.title(column)
    plt.scatter(pd.to_datetime(TRAIN_DF['timestamp']), TRAIN_DF[column], color='k',       s=s, label='Train'  )

    plt.xlabel('Date')
    plt.show()

In [ ]:
DROP_FIELD = ['C01', 'C06', 'C13', 'C14', 'C15', 'C20', 'C21', 'C23', 'C27', 'C28', 
              'C31', 'C33', 'C37', 'C41', 'C56', 'C57', 'C58', 'C59', 'C66', 'C73', 'C79', 'C83',
              'timestamp']
     

In [ ]:

# 상관계수 분석 결과 그룹핑 결과 
[[],
 ['C01', 'C06', 'C33', 'C41', 'C44'],
 ['C03'],
 ['C04'],
 ['C05', 'C14', 'C21', 'C37', 'C40', 'C67', 'C72', 'C74', 'C78', 'C80'],
 ['C05', 'C37', 'C40', 'C67', 'C72', 'C74', 'C78', 'C80'],
 ['C07'],
 ['C08'],
 ['C11'],
 ['C12', 'C31', 'C32', 'C43', 'C70', 'C73', 'C83'],
 ['C12', 'C32', 'C43', 'C70'],
 ['C13'],
 ['C14', 'C21', 'C37', 'C78'],
 ['C15'],
 ['C16', 'C75'],
 ['C17', 'C34', 'C64'],
 ['C20'],
 ['C23', 'C27', 'C28', 'C53', 'C56', 'C65', 'C81'],
 ['C23', 'C27', 'C28', 'C56', 'C81'],
 ['C24', 'C57'],
 ['C25', 'C50'],
 ['C25', 'C50', 'C86'],
 ['C30', 'C48', 'C61', 'C62'],
 ['C31', 'C32', 'C59', 'C70', 'C73', 'C76', 'C83'],
 ['C31', 'C59', 'C73', 'C76', 'C83'],
 ['C35'],
 ['C42'],
 ['C45', 'C47', 'C51'],
 ['C46'],
 ['C50', 'C86'],
 ['C53', 'C65', 'C81'],
 ['C54'],
 ['C58'],
 ['C60'],
 ['C66'],
 ['C68', 'C77'],
 ['C71'],
 ['C79'],
 ['C84']]

[[],
 ['C01', 'C06', 'C33', 'C41', 'C44'],
 ['C03'],
 ['C04'],
 ['C05', 'C14', 'C21', 'C37', 'C40', 'C67', 'C72', 'C74', 'C78', 'C80'],
 ['C05', 'C37', 'C40', 'C67', 'C72', 'C74', 'C78', 'C80'],
 ['C07'],
 ['C08'],
 ['C11'],
 ['C12', 'C31', 'C32', 'C43', 'C70', 'C73', 'C83'],
 ['C12', 'C32', 'C43', 'C70'],
 ['C13'],
 ['C14', 'C21', 'C37', 'C78'],
 ['C15'],
 ['C16', 'C75'],
 ['C17', 'C34', 'C64'],
 ['C20'],
 ['C23', 'C27', 'C28', 'C53', 'C56', 'C65', 'C81'],
 ['C23', 'C27', 'C28', 'C56', 'C81'],
 ['C24', 'C57'],
 ['C25', 'C50'],
 ['C25', 'C50', 'C86'],
 ['C30', 'C48', 'C61', 'C62'],
 ['C31', 'C32', 'C59', 'C70', 'C73', 'C76', 'C83'],
 ['C31', 'C59', 'C73', 'C76', 'C83'],
 ['C35'],
 ['C42'],
 ['C45', 'C47', 'C51'],
 ['C46'],
 ['C50', 'C86'],
 ['C53', 'C65', 'C81'],
 ['C54'],
 ['C58'],
 ['C60'],
 ['C66'],
 ['C68', 'C77'],
 ['C71'],
 ['C79'],
 ['C84']]

In [ ]:
TIMESTAMP_FIELD = "timestamp"
IDSTAMP_FIELD = 'id'
ATTACK_FIELD = "attack"
VALID_COLUMNS_IN_TRAIN_DATASET = TRAIN_DF_RAW.columns.drop(DROP_FIELD)


In [ ]:
TAG_MIN = TRAIN_DF_RAW[VALID_COLUMNS_IN_TRAIN_DATASET].min()
TAG_MAX = TRAIN_DF_RAW[VALID_COLUMNS_IN_TRAIN_DATASET].max()

In [ ]:
def normalize(df):
    ndf = df.copy()
    for c in df.columns:
        if TAG_MIN[c] == TAG_MAX[c]:
            ndf[c] = df[c] - TAG_MIN[c]
        else:
            ndf[c] = (df[c] - TAG_MIN[c]) / (TAG_MAX[c] - TAG_MIN[c])
    return ndf

In [ ]:
def boundary_check(df):
    x = np.array(df, dtype=np.float32)
    print(x)
    return np.any(x > 1.0), np.any(x < 0), np.any(np.isnan(x))

In [ ]:
def flatten(X):
    flattened_X = np.empty((X.shape[0], X.shape[2]))  # sample x features array.
    for i in range(X.shape[0]):
        flattened_X[i] = X[i, (X.shape[1]-1), :]
    return(flattened_X)

def scale(X, scaler):
    for i in range(X.shape[0]):
        X[i, :, :] = scaler.transform(X[i, :, :])
        
    return X

In [ ]:
TRAIN_DF = normalize(TRAIN_DF_RAW[VALID_COLUMNS_IN_TRAIN_DATASET])

In [ ]:
boundary_check(TRAIN_DF)

[[0.         0.05633832 0.5016859  ... 0.         0.         0.27607784]
 [0.         0.05633832 0.5191474  ... 0.         0.         0.27508584]
 [0.         0.05633832 0.5034923  ... 0.         0.         0.27485693]
 ...
 [0.         0.05633832 0.5304673  ... 0.         0.         0.01541396]
 [0.         0.05633832 0.5191474  ... 0.         0.         0.01419306]
 [0.         0.05633832 0.5104769  ... 0.         0.         0.01625334]]


(False, False, False)

In [ ]:
train = np.array(TRAIN_DF)
x_train = train.reshape(train.shape[0], 1, train.shape[1])
x_train.shape

(1004402, 1, 64)

In [ ]:
def conv_auto_model(x):
    n_steps = x.shape[1]
    n_features = x.shape[2]

    keras.backend.clear_session()

    model = keras.Sequential(
        [
            layers.Input(shape=(n_steps, n_features)),
            layers.Conv1D(filters=128, kernel_size=48, padding='same', data_format='channels_last',
                          dilation_rate=1, activation="linear"),
            layers.Dense(128),
            layers.Bidirectional(layers.LSTM(
                units=64, activation="relu", name="lstm_1", return_sequences=False
            )),
            layers.RepeatVector(n_steps),
            layers.Bidirectional(layers.LSTM(
                units=64, activation="relu", name="lstm_2", return_sequences=True
            )),
            layers.Dense(128),
            layers.Conv1D(filters=128, kernel_size=48, padding='same', data_format='channels_last',
                          dilation_rate=1, activation="linear"),
            layers.TimeDistributed(layers.Dense(x.shape[2], activation='linear'))
        ]
    )
    return model

In [ ]:

model = conv_auto_model(x_train)
model.compile(optimizer='adam', loss='mse')
model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d (Conv1D)              (None, 1, 128)            393344    
_________________________________________________________________
dense (Dense)                (None, 1, 128)            16512     
_________________________________________________________________
bidirectional (Bidirectional (None, 128)               98816     
_________________________________________________________________
repeat_vector (RepeatVector) (None, 1, 128)            0         
_________________________________________________________________
bidirectional_1 (Bidirection (None, 1, 128)            98816     
_________________________________________________________________
dense_1 (Dense)              (None, 1, 128)            16512     
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 1, 128)            7

In [ ]:

modelpath = URL+"/"+"_".join(VALID_COLUMNS_IN_TRAIN_DATASET)+"ae_{epoch:02d}-{val_loss:.8f}.hdf5"
checkpointer = ModelCheckpoint(filepath=modelpath, monitor='val_loss', verbose=1, save_best_only=True)
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=5)

epochs = 50
batch = 64

# fit
history = model.fit(x_train, x_train,
                     epochs=epochs, batch_size=batch,
                     validation_split=0.2, callbacks=[checkpointer, early_stopping_callback]).history

Epoch 1/50
12556/12556 [==============================] - 215s 17ms/step - loss: 3.6233e-04 - val_loss: 1.6516e-05

Epoch 00001: val_loss improved from inf to 0.00002, saving model to /content/drive/MyDrive/235757_HAICon2021_dataset.zip (Unzipped Files)/C47_C51ae_01-0.00001652.hdf5
Epoch 2/50
12556/12556 [==============================] - 208s 17ms/step - loss: 1.4641e-05 - val_loss: 8.5391e-07

Epoch 00002: val_loss improved from 0.00002 to 0.00000, saving model to /content/drive/MyDrive/235757_HAICon2021_dataset.zip (Unzipped Files)/C47_C51ae_02-0.00000085.hdf5
Epoch 3/50
12556/12556 [==============================] - 209s 17ms/step - loss: 9.6411e-06 - val_loss: 2.9402e-06

Epoch 00003: val_loss did not improve from 0.00000
Epoch 4/50
12556/12556 [==============================] - 211s 17ms/step - loss: 6.4642e-06 - val_loss: 6.0389e-05

Epoch 00004: val_loss did not improve from 0.00000
Epoch 5/50
 6315/12556 [==============>...............] - ETA: 1:37 - loss: 5.8887e-06

KeyboardInterrupt: ignored

In [ ]:
#model.save(URL+"/models/"+"_".join(USE_FIELD18)+'.h5')

In [ ]:
#model = load_model('./ae_11-0.00002013.hdf5')

# test

In [ ]:
# 메인 모델
model = load_model(URL+'/models/제출용/ae_11-0.00002013.hdf5')


In [ ]:
TEST_DF_RAW = dataframe_from_csvs(TEST_DATASET)
TEST_DF_RAW

timestamp     C01  C02       C03  ...         C83   C84  C85   C86
0       2021-07-13 16:00:01 -2.1424    0  12.37640  ...   981.36951  12.0   50  2100
1       2021-07-13 16:00:02 -2.0449    0  12.37640  ...   981.36951  12.0   50  2165
2       2021-07-13 16:00:03 -2.1287    0  12.37640  ...   981.36951  12.0   50  2209
3       2021-07-13 16:00:04 -2.1287    0  12.37640  ...   981.36951  12.0   50  2233
4       2021-07-13 16:00:05 -2.5969    0  12.37640  ...   981.36951  12.0   50  2290
...                     ...     ...  ...       ...  ...         ...   ...  ...   ...
129595  2021-07-16 23:59:56 -1.8328    0  12.07123  ...  1015.06964  12.0   50    22
129596  2021-07-16 23:59:57 -1.8328    0  12.07123  ...  1015.06964  12.0   50    22
129597  2021-07-16 23:59:58 -1.5833    0  12.07123  ...  1015.06964  12.0   50    22
129598  2021-07-16 23:59:59 -1.4022    0  12.07123  ...  1015.06964  12.0   50    22
129599  2021-07-17 00:00:00 -1.2356    0  12.07123  ...  1015.06964  12.0   50    22

[274800 rows x 87 columns]

In [ ]:
TEST_DF = normalize(TEST_DF_RAW[VALID_COLUMNS_IN_TRAIN_DATASET])

In [ ]:
boundary_check(TEST_DF)

[[0.         0.07981227 0.47904626 ... 0.         0.         0.16879053]
 [0.         0.07981227 0.5016859  ... 0.         0.         0.17375048]
 [0.         0.07981227 0.4808526  ... 0.         0.         0.17710797]
 ...
 [0.         0.01721574 0.4965077  ... 0.         0.         0.01022511]
 [0.         0.01721574 0.5226397  ... 0.         0.         0.01022511]
 [0.         0.01721574 0.5183044  ... 0.         0.         0.01022511]]


(True, True, False)

In [ ]:
test = np.array(TEST_DF)
x_test = test.reshape(test.shape[0], 1, test.shape[1])
x_test.shape

(274800, 1, 64)

In [ ]:
start = time.time()
test_x_predictions = model.predict(x_test)
#print(test_x_predictions)
print(test_x_predictions.shape)
#print((flatten(x_test) - flatten(test_x_predictions)).shape)
test_mse = np.mean(np.power(flatten(x_test) - flatten(test_x_predictions), 2), axis=1)
#test_mse = np.max(np.power(flatten(x_test) - flatten(test_x_predictions), 2), axis=1)

print(test_mse.shape)
print(time.time()-start)

(274800, 1, 64)
(274800,)
83.71448945999146


In [ ]:
test_error = pd.DataFrame({'Reconstruction_error': test_mse})

In [ ]:
move = 60
test_move = test_error['Reconstruction_error'].rolling(move, center=True).mean()
#test_move = test_error['Reconstruction_error'].ewm(span = move, adjust = True,alpha = 0.4).mean()
#test_move = test_error['Reconstruction_error'].ewm(span = move,adjust = True).mean()

test_d = test_move.fillna(0)
test_d

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ... 
274795    0.0
274796    0.0
274797    0.0
274798    0.0
274799    0.0
Name: Reconstruction_error, Length: 274800, dtype: float64

In [ ]:
movemean_test = pd.DataFrame({'Reconstruction_error': test_d})

# TEST PREDICT

In [ ]:
submission = pd.read_csv(URL+'/baseline.csv')
submission.index = submission['timestamp']
#submission['attack'] = pred_y_test
submission

timestamp  attack
timestamp                                       
2021-07-13 16:00:01  2021-07-13 16:00:01     0.0
2021-07-13 16:00:02  2021-07-13 16:00:02     0.0
2021-07-13 16:00:03  2021-07-13 16:00:03     0.0
2021-07-13 16:00:04  2021-07-13 16:00:04     0.0
2021-07-13 16:00:05  2021-07-13 16:00:05     0.0
...                                  ...     ...
2021-07-16 23:59:56  2021-07-16 23:59:56     0.0
2021-07-16 23:59:57  2021-07-16 23:59:57     0.0
2021-07-16 23:59:58  2021-07-16 23:59:58     0.0
2021-07-16 23:59:59  2021-07-16 23:59:59     0.0
2021-07-17 00:00:00  2021-07-17 00:00:00     0.0

[274800 rows x 2 columns]

In [ ]:
def check_graph(xs, att, piece=2, THRESHOLD=None):
    l = xs.shape[0]
    chunk = l // piece
    fig, axs = plt.subplots(piece, figsize=(20, 4 * piece))
    pred_y_test = []
    for i in range(piece):
        L = i * chunk
        R = min(L + chunk, l)
        xticks = range(L, R)
        axs[i].plot(xticks, xs[L:R])

        #Threshold 설정

        pred_tem = [1 if e > THRESHOLD[i] else 0 for e in list(xs[L:R])]
        pred_y_test.extend(pred_tem)

        #SUBPLOT
        if len(xs[L:R]) > 0:
            peak = max(xs[L:R])
            #axs[i].title.set_text(i)
            #axs[i].plot(xticks, att[L:R] * peak * 0.3)
            #axs[i].set_ylim(0,0.01)
        if THRESHOLD!=None:
            axs[i].title.set_text(i)
            axs[i].set_ylim(0,0.0001)
            axs[i].axhline(y=THRESHOLD[i], color='r')
    plt.show()

    pred_y_test
    pred_y_test = np.array(pred_y_test)
    return pred_y_test

In [ ]:
# 기본
auto_threshold = [
0.00006,0.00004,0.00004,0.0001,0.00005,
0.00011,0.000095,0.000085,0.00004,0.00003,
0.000087,0.00003,0.00003,0.00003,0.000032,
0.00003,0.000032,0.000048,0.000036,0.000026]

In [ ]:
pred_y_test = check_graph(test_d, submission['attack'], piece=20, THRESHOLD=auto_threshold)

In [ ]:
submission = pd.read_csv(URL+'/baseline.csv')
submission.index = submission['timestamp']
submission['attack'] = pred_y_test
submission

timestamp  attack
timestamp                                       
2021-07-13 16:00:01  2021-07-13 16:00:01       0
2021-07-13 16:00:02  2021-07-13 16:00:02       0
2021-07-13 16:00:03  2021-07-13 16:00:03       0
2021-07-13 16:00:04  2021-07-13 16:00:04       0
2021-07-13 16:00:05  2021-07-13 16:00:05       0
...                                  ...     ...
2021-07-16 23:59:56  2021-07-16 23:59:56       0
2021-07-16 23:59:57  2021-07-16 23:59:57       0
2021-07-16 23:59:58  2021-07-16 23:59:58       0
2021-07-16 23:59:59  2021-07-16 23:59:59       0
2021-07-17 00:00:00  2021-07-17 00:00:00       0

[274800 rows x 2 columns]

In [ ]:
submission['attack'].value_counts()

0    268923
1      5877
Name: attack, dtype: int64

In [ ]:
#submission.to_csv(URL+"/final_csv/메인 모델 공격(5877).csv",index= False)
#submission.to_csv("6396_1개추가).csv",index= False)

# 다른 공격과 통합하기

In [ ]:
submission = pd.read_csv(URL+"/final_csv/메인 모델 공격(5877).csv")
pred_y_test = list(submission['attack'])

In [ ]:
group3_3 = pd.read_csv(URL+"/final_csv/그룹1(894).csv")
group4_2 = pd.read_csv(URL+"/final_csv/그룹2.csv")
group5_1 = pd.read_csv(URL+"/final_csv/그룹3(199).csv")
group6_1 = pd.read_csv(URL+"/final_csv/추가공격3_private(537).csv")

In [ ]:
for i in range(len(submission)):
    if group3_3['attack'][i] == 1 or group4_2['attack'][i] ==1 or group5_1['attack'][i] == 1 or group6_1['attack'][i] == 1:
        pred_y_test[i] = 1


In [ ]:
submission = pd.read_csv(URL+'/baseline.csv')
submission.index = submission['timestamp']
submission['attack'] = pred_y_test
submission

timestamp  attack
timestamp                                       
2021-07-13 16:00:01  2021-07-13 16:00:01       0
2021-07-13 16:00:02  2021-07-13 16:00:02       0
2021-07-13 16:00:03  2021-07-13 16:00:03       0
2021-07-13 16:00:04  2021-07-13 16:00:04       0
2021-07-13 16:00:05  2021-07-13 16:00:05       0
...                                  ...     ...
2021-07-16 23:59:56  2021-07-16 23:59:56       0
2021-07-16 23:59:57  2021-07-16 23:59:57       0
2021-07-16 23:59:58  2021-07-16 23:59:58       0
2021-07-16 23:59:59  2021-07-16 23:59:59       0
2021-07-17 00:00:00  2021-07-17 00:00:00       0

[274800 rows x 2 columns]

In [ ]:
submission['attack'].value_counts()

0    267730
1      7070
Name: attack, dtype: int64

In [ ]:
submission.to_csv(URL+"/final_csv/최종csv_7070(최종 합친거_0.716).csv",index= False)